' ' Estudo de caso baseado no artigo de modelagem de sistemas industriais, Palazzo e Edelweizz (1998), apud Lutherer E. et al., 1994. 
' ' O estudo representa uma fábrica de concreto que inclui vendas, escritório e a planta industrial. 
' ' A planta é composta de vários receptáculos de armazenagem de cimento, areia, cascalho e água; um misturador para preparação do concreto; duas balanças para pesar os componentes;
' ' uma válvula de medição de componentes; controle de descarga de água; duas esteiras de transporte para levar os ingredientes sólidos ao misturador.
' ' Os clientes preenchem uma ordem de pedido entregue pelo representante com o tipo e quantidade de concreto para entrega em um ou mais dias pela transportadora da empresa.
' ' O departamento de vendas escalona a ordem e eventualmente encaminha a indústria para o encarregado de produção.
' ' A indústria providência a execução do pedido, através da área de produção e de matéria prima.
' ' A produção executa a ordem solicitando materiais que são entregues no local pelo encarregado do almoxarifado e estocagem.
' ' O operador das máquinas executa os controles de fabricação tendo como auxiliares os operários responsáveis pela mistura dos componentes e pelo funcionário encarregado do controle de fluxo de trabalho.
' ' Caso algum produto da matéria prima fique abaixo do nível de segurança, o encarregado da produção emite ordem para o departamento de compras providenciar o pedido da mercadoria que após a entrega é verificado pelo setor de recebimento e distribuição se está entregue conforme foi feito o pedido.
' ' Após a fabricação, o produto é entregue na construção e o cliente efetua o pagamento que é recebido pelo departamento financeiro da indústria.

@startuml

left to right direction

title = Fabrica de Concreto
actor "Clientes" as cl
actor "Representante" as rep
actor "Transportadora" as trans
actor "Departamento de Vendas" as dv
actor "Encarregado de Produção" as ep
actor "Operador de Máquinas" as oma
actor "Operário de Mistura" as omi
actor "Encarregado de Controle de Fluxo de Trabalho" as ea
actor "Encarregado do Almoxarifado e Estocagem" as eae
actor "Setor de Recebimento e Distribuição" as rd
actor "Departamento Financeiro" as df
actor "Departamento de Compras" as dc

package "Sistema de Fabricação de Concreto" {
  usecase "Entregar Ordem de Pedido" as UC1
  usecase "Preencher Ordem de Pedido" as UC2
  usecase "Escalonar Ordem" as UC3
  usecase "Encaminhar à Produção" as UC4
  usecase "Executar Pedido" as UC5
  usecase "Solicitar Materiais" as UC6
  usecase "Entregar Materiais" as UC7
  usecase "Executar Controles de Fabricação" as UC8
  usecase "Misturar Componentes" as UC9
  usecase "Controlar Fluxo do Trabalho" as UC10
  usecase "Emitir Ordem de Compra" as UC11
  usecase "Providenciar o Pedido" as UC12
  usecase "Verificar Entrega" as UC13
  usecase "Entregar Produto" as UC14
  usecase "Efetuar Pagamento" as UC15
  usecase "Receber Pagamento" as UC16  
}

rep -- UC1
cl -- UC2
dv -- UC3
dv -- UC4
ep -- UC5
ep -- UC6
eae -- UC7
oma -- UC8
omi -- UC9
ea -- UC10
ep -- UC11
dc -- UC12
rd -- UC13
trans -- UC14
cl -- UC15
df -- UC16

UC1 -.> UC2 : <<extend>>
UC2 -.> UC3 : <<include>>
UC3 -.> UC4 : <<include>>
UC4 -.> UC5 : <<include>>
UC5 -.> UC6 : <<include>>
UC6 -.> UC7 : <<include>>
UC7 -.> UC8 : <<include>>
UC8 -.> UC9 : <<include>>
UC9 -.> UC10 : <<include>>
UC10 -.> UC11 : <<extend>>
UC11 -.> UC12 : <<include>>
UC12 -.> UC13 : <<include>>
UC13 -.> UC14 : <<include>>
UC10 -.> UC14 : <<include>>
UC14 -.> UC15 : <<include>>
UC15 -.> UC16 : <<include>>

@enduml